- name: Payment setup steps
  hosts: all
  become: true
  tasks:

    - name: Python3 server installtion
      ansible.builtin.dnf:
        name: python3, gcc, python3-devel
        state: latest

    - name: Add the user roboshop
      ansible.builtin.user:
        name: roboshop
    - name: Recursively remove directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Recursively create directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Unarchive a file that needs to be downloaded
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /app
        remote_src: yes

    - name: installing dependencies
      ansible.builtin.shell: pip3 install -r requirements.txt
      args:
        chdir: /app/


    - name: Copy Service file file
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service


    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: restarted
        name: payment
        enabled: true
        daemon-reload: true