- name: Install nodeJS
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: Import App PreReq
  ansible.builtin.import_tasks: AppPrereq.yaml

- name: Import systemd
  ansible.builtin.import_tasks: systemd.yaml

